# Requires 00-upstreams.conf (u_ncb_frontend).

upstream qdrant_igwilo {
    server 127.0.0.1:6333;
    keepalive 8;
}

server {
    listen  80;
    server_name qdrant.igwilo.com www.qdrant.igwilo.com;
    return 301 https://qdrant.igwilo.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name qdrant.igwilo.com;
    ssl_certificate /etc/letsencrypt/live/igwilo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/igwilo.com/privkey.pem;

    client_max_body_size 50M;

    location / {
        proxy_pass http://qdrant_igwilo;
        proxy_http_version 1.1;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host  $server_name;
        proxy_set_header   Connection "";
    }
}
